import { ArrowRight, CheckCircle2, Clock3, Play, ShieldAlert } from 'lucide-react'
import { Link } from 'react-router-dom'
import { completeDocs, docs, sections } from '../data/docs'
import { useLocalStorage } from '../hooks/useLocalStorage'

export default function HomePage() {
  const [completed] = useLocalStorage<string[]>('ltvc-completed', [])
  const next = completeDocs.find(doc => !completed.includes(doc.slug)) ?? completeDocs[0]
  return <div className="home-page cheatsheet-home">
    <section className="home-hero"><div className="hero-copy"><div className="eyebrow">Senior Backend .NET Interview Cheatsheet</div><h1>Đọc nhanh.<br />Trả lời sâu.</h1><p>21 chủ đề có chủ đích. Chỉ giữ mental model, production traps và trade-off thường bị hỏi ở Senior Backend .NET interview.</p><div className="home-actions"><Link className="primary-button" to={`/docs/${next.slug}`}><Play size={17} /> Tiếp tục: {next.title.replace(/^\d+\. /, '')}</Link></div></div><div className="hero-progress"><strong>{completeDocs.length}</strong><span>cheatsheet complete</span><p>{docs.filter(doc => doc.status === 'Draft').length} mục còn trong interview map</p></div></section>
    <section className="quick-start-grid"><Link className="continue-card" to="/interview"><span className="mini-label">Interview mode</span><h2>Random question<br />Reveal answer</h2><p>Luyện câu trả lời 30–60 giây, follow-up và red flags.</p><span className="continue-link">Bắt đầu mock interview <ArrowRight size={16} /></span></Link><div className="goal-card"><div className="goal-icon"><ShieldAlert size={20} /></div><div><span className="mini-label">Cách dùng</span><h2>Không học như textbook</h2></div><ol><li>Chọn câu hỏi hoặc cheatsheet đúng gap.</li><li>Nói short answer trước khi reveal.</li><li>Ghi lại trap/trade-off cần review.</li></ol></div></section>
    {sections.map(section => { const items = docs.filter(doc => doc.section === section); if (!items.length) return null; return <section className="library-section" key={section}><div className="section-heading"><div><span>{section}</span><h2>{section === 'Interview Map' ? 'Bản đồ ôn Senior Backend .NET' : section}</h2></div></div><div className="doc-grid">{items.map(doc => doc.content ? <Link key={doc.slug} className="doc-card" to={`/docs/${doc.slug}`}><div className="doc-card-top"><span className="category-chip">{doc.interviewWeight}</span><span><Clock3 size={14} /> {doc.readingMinutes} phút</span></div><h3>{doc.title}</h3><p>{doc.description}</p><div className="doc-card-action">Mở cheatsheet <ArrowRight size={16} /></div></Link> : <article key={doc.slug} className="doc-card draft-card"><div className="doc-card-top"><span className="category-chip">{doc.status}</span><span>{doc.interviewWeight}</span></div><h3>{doc.title}</h3><p>Đã được định vị trong map; chưa hiển thị nội dung cho đến khi được review.</p></article>)}</div></section> })}
    <section className="study-tip"><CheckCircle2 size={18} /><p><strong>Need Review:</strong> dùng bookmark trên cheatsheet và đánh dấu completed sau khi bạn tự trả lời được câu hỏi, không phải chỉ khi đã đọc xong.</p></section>
  </div>
}
