import { Bookmark, Eye, Shuffle } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { questions } from '../data/docs'
import { useLocalStorage } from '../hooks/useLocalStorage'

export default function InterviewPage() {
  const [topic, setTopic] = useState('All'); const [difficulty, setDifficulty] = useState('All'); const [revealed, setRevealed] = useState<string | null>(null); const [bookmarks, setBookmarks] = useLocalStorage<string[]>('ltvc-question-bookmarks', [])
  const visible = useMemo(() => questions.filter(q => (topic === 'All' || q.topic === topic) && (difficulty === 'All' || q.difficulty === difficulty)), [topic, difficulty])
  const random = () => { const q = visible[Math.floor(Math.random() * visible.length)]; if (q) { setRevealed(q.id); document.getElementById(q.id)?.scrollIntoView({ behavior: 'smooth', block: 'center' }) } }
  const toggle = (id: string) => setBookmarks(items => items.includes(id) ? items.filter(x => x !== id) : [...items, id])
  return <div className="home-page interview-page"><section className="home-hero"><div className="hero-copy"><div className="eyebrow">Interview mode</div><h1>Answer first.<br />Reveal second.</h1><p>Mỗi câu có short answer 30–60 giây, follow-up để đào sâu và red flags cần tránh.</p><button className="primary-button" onClick={random}><Shuffle size={17} /> Random question</button></div></section><div className="question-filters"><select value={topic} onChange={e => setTopic(e.target.value)}><option>All</option>{[...new Set(questions.map(q => q.topic))].map(x => <option key={x}>{x}</option>)}</select><select value={difficulty} onChange={e => setDifficulty(e.target.value)}><option>All</option><option>Senior</option><option>Lead</option></select></div><section className="question-list">{visible.map(q => <article className="question-card" id={q.id} key={q.id}><div><span className="category-chip">{q.topic}</span><span className="weight-badge">{q.difficulty}</span></div><h2>{q.question}</h2><div className="hero-actions"><button className="secondary-button" onClick={() => setRevealed(revealed === q.id ? null : q.id)}><Eye size={17} /> {revealed === q.id ? 'Ẩn answer' : 'Reveal answer'}</button><button className="secondary-button" onClick={() => toggle(q.id)}><Bookmark size={17} /> {bookmarks.includes(q.id) ? 'Đã lưu' : 'Need Review'}</button><Link className="secondary-button" to={`/docs/${q.relatedDoc}`}>Open cheatsheet</Link></div>{revealed === q.id && <div className="answer-panel"><strong>Short answer</strong><p>{q.shortAnswer}</p><strong>Follow-up</strong><ul>{q.followUps.map(x => <li key={x}>{x}</li>)}</ul><strong>Red flags</strong><ul>{q.redFlags.map(x => <li key={x}>{x}</li>)}</ul></div>}</article>)}</section></div>
}
