import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { validateStage2Architecture } from './validate-stage2-security.mjs';

const read = path => readFileSync(path, 'utf8');
const fixture = () => ({ reviewText: read('docs/project/stage-2g-architecture-review.md'), inventoryText: read('docs/project/stage-2g-architecture-inventory.md'), testingReviewText: read('docs/project/stage-2f-testing-review.md'), testingInventoryText: read('docs/project/stage-2f-testing-inventory.md'), deliveryReviewText: read('docs/project/stage-2f-delivery-review.md'), deliveryInventoryText: read('docs/project/stage-2f-delivery-inventory.md'), stage2eReviewText: read('docs/project/stage-2e-security-observability-review.md'), stage2eInventoryText: read('docs/project/stage-2e-production-safety-inventory.md'), mapText: read('docs/roadmap/learning-unit-map.md'), dependencyText: read('docs/roadmap/dependency-map.md'), priorReviewTexts: ['docs/project/stage-2b-foundations-review.md', 'docs/project/stage-2c-data-review.md', 'docs/project/stage-2d-distributed-interaction-review.md'].map(read) });
const errorsAfter = mutate => { const current = fixture(); return validateStage2Architecture({ ...current, ...mutate(current) }).errors; };

test('accepts the complete Stage 2G Architecture package', () => { const result = validateStage2Architecture(fixture()); assert.deepEqual(result.errors, []); assert.deepEqual(result.counts, { required: 18, recommended: 13, targets: 7, internal: 2, fullTargets: 8, candidates: 7 }); assert.equal(result.graph.cycle, false); assert.ok(result.graph.roots > 1); });
test('rejects a missing Architecture relation', () => assert.ok(errorsAfter(({ reviewText }) => ({ reviewText: reviewText.replace(/^\| RECOMMENDED \| arch-evolution-migration-strangler.*\r?\n/m, '') })).some(error => error.includes('missing Architecture relation arch-evolution-migration-strangler -> arch-decision-communication-transfer'))));
test('rejects a duplicate Architecture decision', () => assert.ok(errorsAfter(({ reviewText }) => ({ reviewText: reviewText.replace('| REQUIRED | net-http-semantics -> arch-sync-async-integration', '| REQUIRED | prog-invariants-domain-model -> arch-boundaries-ownership | LOCAL | duplicate | duplicate |\n| REQUIRED | net-http-semantics -> arch-sync-async-integration') })).some(error => error.includes('duplicate active decision Architecture prog-invariants-domain-model -> arch-boundaries-ownership'))));
test('rejects a false multi-Primary Architecture proxy', () => assert.ok(errorsAfter(({ reviewText }) => ({ reviewText: reviewText.replace('arch-boundaries-ownership -> arch-evolution-migration-strangler | EXTERNAL — WHOLE-UNIT PROXY NOT_ACCEPTABLE', 'arch-boundaries-ownership -> arch-evolution-migration-strangler | EXTERNAL — WHOLE-UNIT PROXY ACCEPTABLE') })).some(error => error.includes('false singleton whole-unit proxy arch-boundaries-ownership -> arch-evolution-migration-strangler'))));
test('rejects missing Architecture internal-edge accounting', () => assert.ok(errorsAfter(({ inventoryText }) => ({ inventoryText: inventoryText.replace(/^\| RECOMMENDED \| arch-cost-complexity-changeability.*\r?\n/m, '') })).some(error => error.includes('missing Architecture internal edge arch-cost-complexity-changeability -> arch-decision-communication-transfer'))));
test('rejects a backward edge in the actual combined graph', () => { const current = fixture(); const result = validateStage2Architecture({ ...current, additionalCandidateEdges: [['lu-arch-sync-async-integration', 'lu-arch-requirements-quality-attributes']] }); assert.ok(result.errors.includes('candidate graph cycle')); });
