import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { validateStage2F } from './validate-stage2-security.mjs';

const read = path => readFileSync(path, 'utf8');
const fixture = () => ({ reviewText: read('docs/project/stage-2f-testing-review.md'), inventoryText: read('docs/project/stage-2f-testing-inventory.md'), deliveryReviewText: read('docs/project/stage-2f-delivery-review.md'), deliveryInventoryText: read('docs/project/stage-2f-delivery-inventory.md'), stage2eReviewText: read('docs/project/stage-2e-security-observability-review.md'), stage2eInventoryText: read('docs/project/stage-2e-production-safety-inventory.md'), mapText: read('docs/roadmap/learning-unit-map.md'), dependencyText: read('docs/roadmap/dependency-map.md'), priorReviewTexts: ['docs/project/stage-2b-foundations-review.md', 'docs/project/stage-2c-data-review.md', 'docs/project/stage-2d-distributed-interaction-review.md'].map(read) });
const errorsAfter = mutate => { const current = fixture(); return validateStage2F({ ...current, ...mutate(current) }).errors; };

test('accepts Stage 2F Delivery plus Testing evidence', () => { const result = validateStage2F(fixture()); assert.deepEqual(result.errors, []); assert.deepEqual(result.totals, { relations: 54, required: 23, recommended: 31, targets: 19, internal: 4 }); assert.equal(result.graph.cycle, false); assert.ok(result.graph.roots > 1); });
test('rejects a missing Testing relation', () => assert.ok(errorsAfter(({ reviewText }) => ({ reviewText: reviewText.replace(/^\| RECOMMENDED \| test-review-static-analysis-change-safety.*\r?\n/m, '') })).some(error => error.includes('missing Testing relation test-review-static-analysis-change-safety -> test-risk-transfer'))));
test('rejects a duplicate Testing decision', () => assert.ok(errorsAfter(({ reviewText }) => ({ reviewText: reviewText.replace('| REQUIRED | concurrency-races-check-then-act -> test-time-concurrency-determinism', '| REQUIRED | test-unit-integration-contract -> test-real-dependency-fixtures | LOCAL | duplicate | duplicate |\n| REQUIRED | concurrency-races-check-then-act -> test-time-concurrency-determinism') })).some(error => error.includes('duplicate active decision Testing test-unit-integration-contract -> test-real-dependency-fixtures'))));
test('rejects a false multi-Primary Testing proxy', () => assert.ok(errorsAfter(({ reviewText }) => ({ reviewText: reviewText.replace('test-unit-integration-contract -> test-risk-transfer | EXTERNAL — WHOLE-UNIT PROXY NOT_ACCEPTABLE', 'test-unit-integration-contract -> test-risk-transfer | EXTERNAL — WHOLE-UNIT PROXY ACCEPTABLE') })).some(error => error.includes('false singleton whole-unit proxy test-unit-integration-contract -> test-risk-transfer'))));
test('rejects missing Testing internal-edge accounting', () => assert.ok(errorsAfter(({ inventoryText }) => ({ inventoryText: inventoryText.replace(/^\| test-risk-strategy-boundaries.*\r?\n/m, '') })).some(error => error.includes('invalid Testing internal edge test-risk-strategy-boundaries -> test-unit-integration-contract'))));
test('rejects a backward edge in the actual Stage 2F graph', () => { const current = fixture(); const result = validateStage2F({ ...current, additionalCandidateEdges: [['lu-test-risk-transfer', 'lu-test-failure-resilience']] }); assert.ok(result.errors.includes('candidate graph cycle')); });
